In [24]:
#Final notebook of Santander Customer Satisfaction Case-study

Santander Customer Satisfaction – Which customers are happy customers?” is a Featured Prediction Competition hosted by Kaggle in 2016 on the behalf of “Banco Santander” Bank, which is a large Corporation focusing primarily on the market in the north-eastern part of United States. Kaggle introduces the problem to its readers by harping on the significance of “customer satisfaction” as the key measure of a business success. They further impinge upon the fact that unhappy customers rarely express their dis-satisfaction before leaving. Therefore, it is expected of the participants in the Competition to help identify dis-satisfied customers early on in the relationship so that proactive steps can be taken to improve customer satisfaction early on.The data shared by Santander Bank constitutes of Train-set with 76020 observations, 370 features and one binary target, a Test-set with 75818 observations and 370 features and also a sample submission file. The data consists of hundreds of anonymized features, which are to be leveraged effectively to find an appropriate model and consequently enable prediction with respect to a client’s satisfaction/dis-satisfaction in the near future. In order to evaluate the Machine-Learning models, the evaluation metric used by Santander Bank is “AUC”. The top leadership score obtained was 0.829072. The utility of the model would be that it will help the prestigious Santander Bank to identify dis-satisfied customers as early as possible so that they may be in a position to take necessary action to retain those customers.

In [1]:
#import the libraries
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(palette='muted',style='whitegrid')
from sklearn.manifold import TSNE
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics,ensemble,model_selection,linear_model,tree,calibration
import pandas as pd
import numpy as np


In [2]:
train_data = pd.read_csv('D:/santander_train.csv')
test_data = pd.read_csv('D:/santander_test.csv')

In [3]:
train_data.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   1     2     23                 0.0                      0.0   
1   3     2     34                 0.0                      0.0   
2   4     2     23                 0.0                      0.0   
3   8     2     37                 0.0                    195.0   
4  10     2     39                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                    195.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   
4                      0.0                      0.0  ...   

   saldo_medio_var33_hace2  saldo_medio_var33_hace3  saldo_medio_var33_ult1  \
0                      0.0                      0.0                     0.0   
1                      0.0                      0.0                     0.0   
2                      0.0                      0.0                     0.0   
3                      0.0                      0.0                     0.0   
4                      0.0                      0.0                     0.0   

   saldo_medio_var33_ult3  saldo_medio_var44_hace2  saldo_medio_var44_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var44_ult1  saldo_medio_var44_ult3          var38  TARGET  
0                     0.0                     0.0   39205.170000       0  
1                     0.0                     0.0   49278.030000       0  
2                     0.0                     0.0   67333.770000       0  
3                     0.0                     0.0   64007.970000       0  
4                     0.0                     0.0  117310.979016       0  

[5 rows x 371 columns]

In [4]:
test_data.head()

ID  var3  var15  imp_ent_var16_ult1  imp_op_var39_comer_ult1  \
0   2     2     32                 0.0                      0.0   
1   5     2     35                 0.0                      0.0   
2   6     2     23                 0.0                      0.0   
3   7     2     24                 0.0                      0.0   
4   9     2     23                 0.0                      0.0   

   imp_op_var39_comer_ult3  imp_op_var40_comer_ult1  imp_op_var40_comer_ult3  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   imp_op_var40_efect_ult1  imp_op_var40_efect_ult3  ...  \
0                      0.0                      0.0  ...   
1                      0.0                      0.0  ...   
2                      0.0                      0.0  ...   
3                      0.0                      0.0  ...   
4                      0.0                      0.0  ...   

   saldo_medio_var29_ult3  saldo_medio_var33_hace2  saldo_medio_var33_hace3  \
0                     0.0                      0.0                      0.0   
1                     0.0                      0.0                      0.0   
2                     0.0                      0.0                      0.0   
3                     0.0                      0.0                      0.0   
4                     0.0                      0.0                      0.0   

   saldo_medio_var33_ult1  saldo_medio_var33_ult3  saldo_medio_var44_hace2  \
0                     0.0                     0.0                      0.0   
1                     0.0                     0.0                      0.0   
2                     0.0                     0.0                      0.0   
3                     0.0                     0.0                      0.0   
4                     0.0                     0.0                      0.0   

   saldo_medio_var44_hace3  saldo_medio_var44_ult1  saldo_medio_var44_ult3  \
0                      0.0                     0.0                     0.0   
1                      0.0                     0.0                     0.0   
2                      0.0                     0.0                     0.0   
3                      0.0                     0.0                     0.0   
4                      0.0                     0.0                     0.0   

       var38  
0   40532.10  
1   45486.72  
2   46993.95  
3  187898.61  
4   73649.73  

[5 rows x 370 columns]

In [5]:
print("The number of observations in Santander Train-Data are:",train_data.shape[0])
print("The number of features in Santander Train-Data are:",test_data.shape[1])

The number of observations in Santander Train-Data are: 76020
The number of features in Santander Train-Data are: 370


In [6]:
print("The number of observations in Santander Test-Data are:",test_data.shape[0])
print("The number of features in Santander Train-Data are:",test_data.shape[1])

The number of observations in Santander Test-Data are: 75818
The number of features in Santander Train-Data are: 370


In [7]:
Xi_train = pd.read_pickle(r'D:/Xi_train_santander.pickle')

In [8]:
Xi_train.shape

(76020, 882)

In [9]:
yi_train = pd.read_pickle(r'D:/yi_train_santander.pickle')

In [10]:
yi_train.shape

(76020,)

In [11]:
def feature_encoding(train_df):
    categorical_feat = []
    for column in train_df.columns: #identify features which have less than or equal to 10 unique values
        if (train_df[column].nunique()<=10) & (column!='TARGET') & (train_df[column].nunique()>2) & (column!='ID'):
            categorical_feat.append(column)
            
    caty_feat_two = []
    for column in train_df.columns: #identify features which have only two unique values
        if (train_df[column].nunique()==2) & (column!='TARGET') & (column!='ID'):
            caty_feat_two.append(column)
            
    caty_feat_one = []
    for column in train_df.columns: #identify features which have only 1 unique value
        if (train_df[column].nunique()==1) & (column!='TARGET') & (column!='ID'):
            caty_feat_one.append(column)
            
    numerical_feat = []
    for column in train_df.columns: #identify features which have more than 10 unique values
        if (train_df[column].nunique()>10) & (column!='TARGET') & (column!='ID'):
            numerical_feat.append(column)
            
    return categorical_feat, caty_feat_two, caty_feat_one, numerical_feat
            
            
            
    

In [12]:
def feature_train_encoding(train_df, categorical_feat, caty_feat_two, caty_feat_one, numerical_feat ):
    print(train_df[categorical_feat].shape)
    print(train_df[caty_feat_two].shape)
    print(train_df[caty_feat_one].shape) #caty feat_one
    print(train_df[numerical_feat].shape)
    
    from sklearn import preprocessing 
    min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
  
    # Scaled feature
    train_data_num = min_max_scaler.fit_transform(train_df[numerical_feat])
  
    print ("\nAfter min max Scaling : \n")
    print("shape", train_data_num.shape) #test_data_num
  
    """ Standardisation """
  
    Standardisation = preprocessing.StandardScaler()
  
    # Scaled feature
    train_data_numy = Standardisation.fit_transform(train_df[numerical_feat])
  
    print ("\nAfter Standardisation : \n")
    print("shape", train_data_numy.shape)
    
    from sklearn.preprocessing import OneHotEncoder


    enc = OneHotEncoder(handle_unknown = 'ignore')
    enc.fit(train_df[categorical_feat])

    train_data_cat = enc.transform(train_df[categorical_feat]).toarray()

    #enc_df = pd.DataFrame(enc.fit_transform(bridge_df[['Bridge_Types_Cat']]).toarray())

    print("After vectorizations")
    print(train_data_cat.shape)  #test_data_cat
    
    enc = OneHotEncoder(handle_unknown = 'ignore')
    enc.fit(train_df[caty_feat_two])

    train_data_cat_two = enc.transform(train_df[caty_feat_two]).toarray()

    #enc_df = pd.DataFrame(enc.fit_transform(bridge_df[['Bridge_Types_Cat']]).toarray())

    print("After vectorizations")
    print(train_data_cat_two.shape)  #test_data_cat_two
    
    #enc = OneHotEncoder(handle_unknown = 'ignore')
    #enc.fit(test_data_cat_two_array)

    #test_data_cat_two_arr = enc.transform(test_data_cat_two_array)

    #print("After vectorizations")
    #print(test_data_cat_two_arr.shape)
    
    train_data_cat_one = np.array(train_df[caty_feat_one])
    
    print(train_data_cat_one.shape) #test_data_cat_one
    
    print("data type of test_data_cat is:", type(train_data_cat))
    print("data type of test_data_cat_two is:", type(train_data_cat_two))
    print("data type of test_data_cat_one is", type(train_data_cat_one))
    print("data type of test_data_num is", type(train_data_num))
    print("Shape of test_data_cat is:", (train_data_cat.shape))
    print("Shape of test_data_cat_two is:", (train_data_cat_two.shape))
    print("Shape of test_data_cat_one is", (train_data_cat_one.shape))
    print("Shape of test_data_num is", (train_data_num.shape))
    
    
    return train_data_cat, train_data_cat_two, train_data_cat_one, train_data_num

    



In [13]:
def feature_test_encoding(train_df, test_df, categorical_feat, caty_feat_two, caty_feat_one, numerical_feat ):
    from sklearn.preprocessing import OneHotEncoder

    enc = OneHotEncoder(handle_unknown = 'ignore')
    enc.fit(train_df[categorical_feat])
    test_data_cat = enc.transform(test_data[categorical_feat]).toarray()
    print("Shape of test_data_cat is:",test_data_cat.shape)
    
    enc.fit(train_data[caty_feat_two])
    test_data_cat_two = enc.transform(test_data[caty_feat_two]).toarray()
    print("Shape of test_data_cat_two is:",test_data_cat_two.shape)
    
    test_data_cat_one = np.array(test_data[caty_feat_one])
    print("Shape of test_data_cat_one is:",test_data_cat_one.shape)
    
    from sklearn import preprocessing  #Ref: https://www.geeksforgeeks.org/ml-feature-scaling-part-2/
    min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
    test_data_num = min_max_scaler.fit_transform(test_data[numerical_feat])
    print ("\nAfter min max Scaling : \n", test_data_num)
    print("shape of test_data_num is:", test_data_num.shape)
    
    return test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num
  
    

    


In [14]:
def feature_stacking(test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num):
    from scipy.sparse import hstack #stack sparse matrices horizontally
    #Xi_train=np.hstack([train_data_cat, train_data_cat_two, train_data_cat_one, train_data_num])
    #print(Xi_train.shape)
    #test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num = feature_test_encoding(test)
    Xi_test=np.hstack([test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num])
    print("Shape of dataset after stacking is:", Xi_test.shape)
    return Xi_test

In [15]:
def modelling(X_test):
    """
    returns y_test after prediction
    """
    import joblib
    filepath = 'E:/light_gbm_santander_model_case_study.sav'
    with open(filepath,'rb') as file:
        model = joblib.load(file)
    y_test = model.predict_proba(X_test)  #[:,1]
    #y_test = (model.predict_proba(X_test) >= 0.5).astype(bool) #[:,1]
    threshold = 0.5
    y_test = [1 if x >= threshold else 0 for x in y_test[:,1]] #y_test[:, 1]
    return y_test

In [16]:
def final1(train, test):
    """
    returns y_pred on giving an input
    """
   
    y_train = train['TARGET'].values
    train = train.drop(['ID'],axis=1)
    
    test = test.drop('ID',axis=1)
    
    categorical_feat, caty_feat_two, caty_feat_one, numerical_feat = feature_encoding(train)
    test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num = feature_test_encoding(train, test, categorical_feat, caty_feat_two, caty_feat_one, numerical_feat)
    Xi_test = feature_stacking(test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num)
    y_pred = modelling(Xi_test)
    
    return (y_pred)

In [17]:
def final2(train, test, y_test):
    """
    returns auc score 
    """

    y_train = train['TARGET'].values
    train = train.drop(['ID','TARGET'],axis=1)
   
    test = test.drop('ID',axis=1)
    
    categorical_feat, caty_feat_two, caty_feat_one, numerical_feat = feature_encoding(train)
    test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num = feature_test_encoding(train, test, categorical_feat, caty_feat_two, caty_feat_one, numerical_feat)
    Xi_test = feature_stacking(test_data_cat, test_data_cat_two, test_data_cat_one, test_data_num)
    y_pred = modelling(Xi_test)

    auc_score = metrics.roc_auc_score(y_test,y_pred)
    return auc_score

In [18]:
import itertools

In [19]:
%time y_pred = final1(train_data, test_data)

Shape of test_data_cat is: (75818, 507)
Shape of test_data_cat_two is: (75818, 210)
Shape of test_data_cat_one is: (75818, 34)

After min max Scaling : 
 [[0.99976406 0.27       0.         ... 0.         0.         0.0013612 ]
 [0.99976406 0.3        0.         ... 0.         0.         0.00153268]
 [0.99976406 0.18       0.         ... 0.         0.         0.00158484]
 ...
 [0.99976406 0.19       0.         ... 0.         0.         0.00574866]
 [0.99976406 0.35       0.         ... 0.         0.         0.00401853]
 [0.99976406 0.18       0.         ... 0.         0.         0.00401853]]
shape of test_data_num is: (75818, 131)
Shape of dataset after stacking is: (75818, 882)
Wall time: 4.34 s


In [20]:
print(y_pred)

[1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 

In [21]:
type(y_pred)

list

In [22]:
len(y_pred)

75818

In [23]:
y_pred = np.asarray(y_pred)

In [24]:
len(y_pred)

75818

In [25]:
submission = pd.DataFrame({
    "Id": test_data["ID"],
    "Target": y_pred.astype(int)
})

submission.to_csv("E:/kaggle_new.csv", index = False)

In [26]:
df = pd.read_csv("E:/kaggle_new.csv")
print(df.head(5))

   Id  Target
0   2       1
1   5       1
2   6       0
3   7       0
4   9       0


In [27]:
df.shape

(75818, 2)

# Now, passing selected data points

In [28]:
%time
y_test_one = final1(train_data, test_data.loc[[0, 1, 2], :])

Wall time: 0 ns
Shape of test_data_cat is: (75818, 507)
Shape of test_data_cat_two is: (75818, 210)
Shape of test_data_cat_one is: (75818, 34)

After min max Scaling : 
 [[0.99976406 0.27       0.         ... 0.         0.         0.0013612 ]
 [0.99976406 0.3        0.         ... 0.         0.         0.00153268]
 [0.99976406 0.18       0.         ... 0.         0.         0.00158484]
 ...
 [0.99976406 0.19       0.         ... 0.         0.         0.00574866]
 [0.99976406 0.35       0.         ... 0.         0.         0.00401853]
 [0.99976406 0.18       0.         ... 0.         0.         0.00401853]]
shape of test_data_num is: (75818, 131)
Shape of dataset after stacking is: (75818, 882)


In [29]:
y_test_one

[1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,


In [30]:
%time
y_test_point = final1(train_data, test_data.loc[[3], :])

Wall time: 0 ns
Shape of test_data_cat is: (75818, 507)
Shape of test_data_cat_two is: (75818, 210)
Shape of test_data_cat_one is: (75818, 34)

After min max Scaling : 
 [[0.99976406 0.27       0.         ... 0.         0.         0.0013612 ]
 [0.99976406 0.3        0.         ... 0.         0.         0.00153268]
 [0.99976406 0.18       0.         ... 0.         0.         0.00158484]
 ...
 [0.99976406 0.19       0.         ... 0.         0.         0.00574866]
 [0.99976406 0.35       0.         ... 0.         0.         0.00401853]
 [0.99976406 0.18       0.         ... 0.         0.         0.00401853]]
shape of test_data_num is: (75818, 131)
Shape of dataset after stacking is: (75818, 882)


In [31]:
y_test_point

[1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,


In [32]:
len(y_test_point)

75818

In [33]:
#Thank you